### PR TITLE
test updated byteplay with support for 3.6

### PR DESCRIPTION
**Pull request by ndawe**

### CODE REVIEW

**Comment by beojan** [comment]
That still doesn't seem to work for me. First, I have to replace 
`from wbyteplay import *` with `from .wbyteplay import *` in `byteplay3/__init__.py`. Then, I still get the error 
```
AttributeError: module 'rootpy.extern.byteplay3' has no attribute 'MAKE_CLOSURE'
```

**Comment by ndawe** [comment]
https://docs.python.org/3/whatsnew/3.6.html#cpython-bytecode-changes

MAKE_CLOSURE opcode has been removed in 3.6... Hmm...

I think I really need to remove the byteplay magic. This will only continue to cause problems in the future...

Working on it!

**Comment by ndawe** [comment]
Actually, I think I can use MAKE_FUNCTION instead of MAKE_CLOSURE. Comparing the bytecode of the following closure between 2.7 and 3.6:

```python
def foo():
    newsuper = super
    def bar(*args, **kwargs):
        j = 1
        return newsuper(*args, **kwargs)
    return bar

from dis import dis
print(dis(foo))
```

```
python test_closure.py 
  3           0 LOAD_GLOBAL              0 (super)
              3 STORE_DEREF              0 (newsuper)

  4           6 LOAD_CLOSURE             0 (newsuper)
              9 BUILD_TUPLE              1
             12 LOAD_CONST               1 (<code object bar at 0x7fd11649e2b0, file "test_closure.py", line 4>)
             15 MAKE_CLOSURE             0
             18 STORE_FAST               0 (bar)

  7          21 LOAD_FAST                0 (bar)
             24 RETURN_VALUE 
```

```
python3.6 test_closure.py 
  3           0 LOAD_GLOBAL              0 (super)
              2 STORE_DEREF              0 (newsuper)

  4           4 LOAD_CLOSURE             0 (newsuper)
              6 BUILD_TUPLE              1
              8 LOAD_CONST               1 (<code object bar at 0x7f45b079a8a0, file "test_closure.py", line 4>)
             10 LOAD_CONST               2 ('foo.<locals>.bar')
             12 MAKE_FUNCTION            8
             14 STORE_FAST               0 (bar)

  7          16 LOAD_FAST                0 (bar)
             18 RETURN_VALUE

```

**Comment by ndawe** [comment]
Continuing in #745 with a different branch. I think my changes should work in 3.6. Feel free to test as well.

**Pull request closed without merging**
