### PR TITLE
Extended glob module to access remote file systems

### PR DESCRIPTION
**Pull request by benkrikler**
I noticed that when using the TreeChain class there was no reproduction of the way ROOT's `TChain::Add` method handles wild-cards for files on remote file-systems, such as Xrootd.  This PR adds a new `ext_glob` module which provides a similar interface to the normal python `glob` module, but with the ability to check for files on remote file systems via calls to `TSystem`.   The underlying method implementation is recursive, so it can handle wild-cards in directories as well as in the base-name (unlike `TChain::Add`).  The list of files returned via `ext_glob.glob(...)` can then be fed directly into TreeChain

I've also added some unit tests for the new module, however I'm not sure how to unit test remote access given that on many systems such access will not exist.  I'm happy to add this in but since I'm a little new to unit testing python it would be great for some guidance!

### CODE REVIEW

**Comment by ndawe** [comment]
Nice work.

For the unit testing just use "nose" instead of unittest and write simple functions for each test like what is done in the histogram tests:

https://github.com/rootpy/rootpy/blob/master/rootpy/plotting/tests/test_hist.py

**Comment by ndawe** [comment]
The default unit tests should run without a network connection so the tests that glob locally are fine. You could also add tests that glob remotely and decorate those with ``@attr('network')`` like here:

https://github.com/rootpy/rootpy/blob/master/rootpy/tests/test_stl.py#L45

Then we can skip those tests requiring network access in the default set of tests that are run in the continuous integration by adding "-a '!network'" to:

https://github.com/rootpy/rootpy/blob/master/Makefile#L58

```
nosetests -v -a '!slow' -a '!network' -s --exclude=extern rootpy
```

**Comment by ndawe** [comment]
Correction. Probably something like:

```
nosetests -v  -A "not slow and not network" -s --exclude=extern rootpy
```

**Comment by benkrikler** [comment]
Thanks for all the feedback!

I've added two unit tests to check files on an xrootd file system.  I tried to find a directory that would be reasonably public to test against, and as such I am testing a directory in `eos`, under eospublic.  There might be a more appropriate directory to check but the way the tests are written it should now be a simple case of changing a value of the `remote_directory` variable.  I also only check that the list of files is reasonably large, rather than inspect the specific values of the list returned, which would make the check very dependent on the path we inspect.

I've changed the makefile so that `make test` also skips the unit tests that have the `network` attribute set.  

Let me know if there are other comments or suggestions.

**Comment by ndawe** [comment]
Looks good to me. Thanks again for this contribution. I'm pressing the green button.

**Pull request merged**
