### PR TITLE
Test examples on travis-ci

### PR DESCRIPTION
**Pull request by cdeil**
@ndawe – I'm getting some errors from the examples locally and don't know if it's an issue with my setup or whether they are really broken. Can we run the examples on travis-ci?

### CODE REVIEW

**Comment by cdeil** [comment]
So this one also fails on travis-ci:
https://travis-ci.org/rootpy/rootpy/jobs/65045061#L1543
For this one and a few others I see locally I don't know how to fix them, so @ndawe, if you want to take this over or start from master I would be happy.

Is there a way to run all examples even if there is a fail in one?
`make -k` doesn't work.

I've also attached a commit fixing `print` statements for Python 3.
There's also some Sphinx extensions and modules in `extern` that don't work on Python 3 and need to be updated.

**Comment by ndawe** [comment]
I'm cherry-picking babeaec and will open a PR

**Comment by ndawe** [comment]
Getting the examples running on travis will take a bit of extra work. I'll at least merge the py3 fixes.

**Comment by cdeil** [comment]
I think there's nothing here to be merged any more. Closing this PR.

**Pull request closed without merging**
